# Generated by Django 2.1.1 on 2020-06-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_make', models.TextField(help_text="vehicle's make", max_length=30)),
                ('is_commercial', models.BooleanField(default=False, help_text='true if commercial vehicle, false if private. default is false')),
                ('v_plate', models.TextField(help_text="vehicle's license plate", max_length=10)),
                ('owner', models.TextField(help_text="vehicle's owner", max_length=30)),
                ('status', models.TextField(choices=[('go', 'good'), ('st', 'stolen')], default='go', help_text="vehicle's current reported status")),
                ('registration', models.TextField(blank=True, help_text='vehicle registration', max_length=30, null=True)),
                ('v_model', models.TextField(blank=True, help_text="vehicle's model", max_length=30, null=True)),
                ('v_state', models.TextField(blank=True, help_text="vehicle's state of registration", max_length=30, null=True)),
                ('v_country', models.TextField(blank=True, help_text="vehicle's country of registration", max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(help_text="driver's first name", max_length=30)),
                ('last_name', models.TextField(help_text="driver's last name", max_length=30)),
                ('license_num', models.TextField(help_text="driver's license number", max_length=20, unique=True)),
                ('license_expiry', models.DateField(help_text="driver's license expiration date")),
                ('state', models.TextField(blank=True, help_text="State for the driver's license", max_length=30)),
                ('country', models.TextField(help_text="Country for the driver's license", max_length=30)),
                ('phone_num', models.TextField(help_text="the driver's phone number", max_length=12)),
                ('dob', models.DateField(blank=True, help_text="driver's date of birth", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(help_text='Company issuing insurance', max_length=200)),
                ('policy_num', models.TextField(help_text='Insurance Policy number', max_length=30, unique=True)),
                ('expiry', models.DateField(help_text='Insurance expiration date')),
                ('coverage_type', models.TextField(help_text='type of insurance coverage', max_length=30)),
                ('status', models.TextField(choices=[('ex', 'Expired'), ('ac', 'Active'), ('su', 'Suspended')], default='ac', help_text="vehicle's current insurance status")),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='povreg.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_num', models.TextField(help_text="officer's badge number", max_length=30, unique=True)),
                ('unit', models.TextField(help_text="officer's division, district, or unit", max_length=30)),
                ('region', models.TextField(help_text="officer's operating region (country, state, province)", max_length=30)),
                ('id_num', models.TextField(help_text="officer's personal ID number", max_length=30, unique=True)),
                ('first_name', models.TextField(blank=True, help_text="officer's first name", max_length=30, null=True)),
                ('last_name', models.TextField(blank=True, help_text="officer's last name", max_length=30, null=True)),
                ('rank', models.TextField(blank=True, help_text="officer's current rank", max_length=30, null=True)),
                ('id_photo', models.TextField(blank=True, help_text="upload of the officer's photo ID", null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='povreg.Driver'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='povreg.Insurance'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('v_plate', 'v_state', 'v_country')},
        ),
    ]
