# Generated by Django 2.1.1 on 2020-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0002_auto_20200617_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.TextField(choices=[('go', 'good'), ('st', 'stolen')], default='go', help_text="vehicle's current reported status"),
        ),
    ]
