# Generated by Django 2.1.1 on 2020-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0004_auto_20200618_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.TextField(choices=[('go', 'good'), ('st', 'stolen')], default='go', help_text="vehicle's current reported status"),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.TextField(choices=[('ex', 'Expired'), ('su', 'Suspended'), ('ac', 'Active')], default='ac', help_text="vehicle's current insurance status"),
        ),
    ]
