# Generated by Django 2.1.1 on 2020-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0006_auto_20200618_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.TextField(choices=[('ex', 'Expired'), ('ac', 'Active'), ('su', 'Suspended')], default='ac', help_text="vehicle's current insurance status"),
        ),
    ]
