# Generated by Django 2.1.1 on 2020-07-04 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0008_auto_20200704_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='This is the user account that corresponds to the driver', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.TextField(choices=[('ex', 'Expired'), ('ac', 'Active'), ('su', 'Suspended')], default='ac', help_text="vehicle's current insurance status"),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='this is the user account connected to this officer', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
