# Generated by Django 2.1.1 on 2020-07-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0009_auto_20200704_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.TextField(choices=[('su', 'Suspended'), ('ex', 'Expired'), ('ac', 'Active')], default='ac', help_text="vehicle's current insurance status"),
        ),
    ]
