# Generated by Django 2.1.1 on 2020-07-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0010_auto_20200705_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.TextField(choices=[('st', 'stolen'), ('go', 'good')], default='go', help_text="vehicle's current reported status"),
        ),
    ]
