# Generated by Django 2.1.1 on 2020-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0011_auto_20200705_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.TextField(choices=[('good', 'good'), ('stolen', 'stolen')], default='go', help_text="vehicle's current reported status"),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expired', 'Expired')], default='Active', help_text="vehicle's current insurance status"),
        ),
    ]
