# Generated by Django 2.1.1 on 2020-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povreg', '0012_auto_20200711_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.TextField(help_text='vehicle registration', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.TextField(choices=[('stolen', 'stolen'), ('good', 'good')], default='go', help_text="vehicle's current reported status"),
        ),
        migrations.AlterField(
            model_name='car',
            name='v_country',
            field=models.TextField(help_text="vehicle's country of registration", max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='v_model',
            field=models.TextField(help_text="vehicle's model", max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='v_plate',
            field=models.TextField(help_text="vehicle's license plate", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='v_state',
            field=models.TextField(help_text="vehicle's state of registration", max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(help_text="driver's date of birth"),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.TextField(choices=[('Suspended', 'Suspended'), ('Active', 'Active'), ('Expired', 'Expired')], default='Active', help_text="vehicle's current insurance status"),
        ),
        migrations.AlterField(
            model_name='officer',
            name='first_name',
            field=models.TextField(help_text="officer's first name", max_length=30),
        ),
        migrations.AlterField(
            model_name='officer',
            name='last_name',
            field=models.TextField(help_text="officer's last name", max_length=30),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.TextField(help_text="officer's current rank", max_length=30),
        ),
    ]
